2023-06-20 20:02:35,136 ERROR: Exception on /auth/reset_password_request [POST] [in /Users/weixia/Documents/repo/microblog/venv/lib/python3.8/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/Users/weixia/Documents/repo/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/weixia/Documents/repo/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/weixia/Documents/repo/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/weixia/Documents/repo/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/weixia/Documents/repo/microblog/app/auth/routes.py", line 59, in reset_password_request
    send_password_reset_email(user)
  File "/Users/weixia/Documents/repo/microblog/app/auth/email.py", line 6, in send_password_reset_email
    token = user.get_reset_password_token()
  File "/Users/weixia/Documents/repo/microblog/app/models.py", line 72, in get_reset_password_token
    app.config['SECRET_KEY'], algorithm='HS256')
NameError: name 'app' is not defined
2023-06-20 20:06:57,383 INFO: Microblog startup [in /Users/weixia/Documents/repo/microblog/app/__init__.py:72]
2023-06-20 20:07:08,823 ERROR: Exception on /auth/reset_password_request [POST] [in /Users/weixia/Documents/repo/microblog/venv/lib/python3.8/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/Users/weixia/Documents/repo/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/weixia/Documents/repo/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/weixia/Documents/repo/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/weixia/Documents/repo/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/weixia/Documents/repo/microblog/app/auth/routes.py", line 59, in reset_password_request
    send_password_reset_email(user)
  File "/Users/weixia/Documents/repo/microblog/app/auth/email.py", line 10, in send_password_reset_email
    text_body=render_template('email/reset_password.txt',
  File "/Users/weixia/Documents/repo/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
  File "/Users/weixia/Documents/repo/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
  File "/Users/weixia/Documents/repo/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/weixia/Documents/repo/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/weixia/Documents/repo/microblog/app/templates/email/reset_password.txt", line 5, in top-level template code
    {{ url_for('reset_password', token=token, _external=True) }}
  File "/Users/weixia/Documents/repo/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/Users/weixia/Documents/repo/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/Users/weixia/Documents/repo/microblog/venv/lib/python3.8/site-packages/werkzeug/routing/map.py", line 950, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'reset_password' with values ['token']. Did you mean 'auth.reset_password' instead?
2023-06-20 20:08:21,485 INFO: Microblog startup [in /Users/weixia/Documents/repo/microblog/app/__init__.py:72]
2023-06-20 20:37:36,095 INFO: Microblog startup [in /Users/weixia/Documents/repo/microblog/app/__init__.py:72]
